### ISSUE TITLE
[Firemonkey] Icon popup sizing / cutoff issue

### ISSUE THREAD

**Issue by Tharn** [erosman/support#279]
On my desktop everything is fine (1680x1050), on my laptop the popup is not very usable (1280x800). See here:

![firemonkey](https://user-images.githubusercontent.com/13466852/106199857-513fa600-61b6-11eb-91ba-a8769c9cb0a7.png)

Edit: I followed a github link, this may be in the wrong repository. Sorry about that!

**Comment by Tharn** [comment]
Thanks. Let's see.. font settings are as follows:

![fonts](https://user-images.githubusercontent.com/13466852/106204968-117cbc80-61be-11eb-977f-a264a577b243.png)

**Comment by erosman** [comment]
This is what I have which is the default

![image](https://user-images.githubusercontent.com/6458876/106235986-2b93ba80-6211-11eb-8d0c-47eff5f34769.png)

![image](https://user-images.githubusercontent.com/6458876/106236259-b5438800-6211-11eb-9a33-7a9186b55130.png)



Are the font settings the same on your laptop & desktop?
Can you set the fonts to the defaults and try?

**Comment by rubaboo** [comment]
I have the same issue. I believe it's due to scaling. I don't think my scaling settings are unreasonable, given the size of the display and the pixel density. Here is a screenshot of display settings on my laptop followed by full-height screenshot with the extension menu cut off. The scaling is what's also causing screenshots to be huge, unless I resize them before posting.

![image](https://user-images.githubusercontent.com/212368/106245893-1c395080-61c2-11eb-81a2-fdd2c0d6bda0.png)

![image](https://user-images.githubusercontent.com/212368/106245911-22c7c800-61c2-11eb-8ad1-2692e4e1658f.png)

**Comment by erosman** [comment]
I see.... that makes sense.

I will see if there is a possibility to detect scaling.

**Comment by Tharn** [comment]
Yes, on Desktop (Win 10) I have the same fonts and Firemonkey scales perfectly there.

My Windows scaling is at 100% btw.

**Comment by erosman** [comment]
Checking the image from Tharn, it does appear that there is no scaling since the script names appear the usual size.

I am going to ask around to see if anyone know why that happens.

**Comment by erosman** [comment]
BTW, was the problem like that before? or is it a recent issue?

In v2.8. I made changes to popup fix #270 
I wonder if that is the reason although it doesn't explain why it is different in (1680x1050) vs (1280x800) :thinking:

**Comment by Tharn** [comment]
I'll try a reinstall.
Not sure when this started, but I've not used the popup much for this reason. There is still right-click -> options.

**Comment by erosman** [comment]
After install and before importing the options, did you try the popup (without any scripts installed)?


Do you know how to start with a new profile in Firefox?
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Multiple_profiles

Create a new clean profile, launch it, then install FireMonkey and test

**Comment by Tharn** [comment]
Yes, tried it before importing settings, and also just tried it with a new profile. Both produce a bad popup.

**Comment by erosman** [comment]
I have already asked around but got no answer so far.

I have to find out what is wrong (or be able to reproduce it) in order to fix it. :man_shrugging:

**Comment by erosman** [comment]
[Debugging popups](https://extensionworkshop.com/documentation/develop/debugging/#debugging-popups)

Do you know how to use the debugger?

Go to: **about:debugging#/runtime/this-firefox -> FireMonkey -> Inspect**

From the 3-dot menu (top-right) select **Disable Popup Auto-Hide**. Click to open the popup and from the menu next to the 3-dot menu choose the `popup.html`

![image](https://user-images.githubusercontent.com/6458876/106308994-be1a7500-6276-11eb-83dc-a5e8ec79416c.png)

Then you have to look around to see if there is something that causes the **width** to be changed. e.g. under **Rules** or **Layout**

![image](https://user-images.githubusercontent.com/6458876/106309654-aee7f700-6277-11eb-9035-3639e76b9130.png)

![image](https://user-images.githubusercontent.com/6458876/106309259-1b162b00-6277-11eb-9701-8d6f2340061f.png)

Once done, deselect **Disable Popup Auto-Hide** to return to normal.

**Comment by Tharn** [comment]
This is what I got:

![fm1](https://user-images.githubusercontent.com/13466852/106311989-46dce500-6266-11eb-922b-e8aa818c225e.png)

![fm2](https://user-images.githubusercontent.com/13466852/106311995-493f3f00-6266-11eb-83d8-ca96664dd0be.png)

**Comment by erosman** [comment]
OK.. That was helpful. :+1:   

The reason is the adjustment that was made in v2.8 (as showed in the 2nd image)

Why it happens in your desktop, I don't know ... but .... I will work something out for the next update.

**Comment by Tharn** [comment]
Since it doesn't happen to you, feel free to share betas here and I'll check them out.

**Comment by erosman** [comment]
You can test it by .......

Go back to the debugging as previous post and open the popup and select `popup.html`

On Toolbox -> **Style Editor -> line 42**

change:
```css
@media (min-width: 340px) {
```
to:
```css
@media screen and (min-width: 340px) and (max-width: 425px) {
```

Let's see ....

**Comment by erosman** [comment]
Uploaded v2.18

- Fixed an issue with hashed URLs and Tab script list in Toolbar Pop-up
- Reverted overflow menu CSS (from 2.8) (bug 1373490)

**Comment by Tharn** [comment]
You were too fast, lol.
Unfortunately, I still get the issue in 2.17, tested with a fresh profile.

**Comment by erosman** [comment]
Can you post another screenshot of the debugger like last time?

**Comment by Tharn** [comment]
Sure. I played around with it a little.. adding a `height` item allows me to change height, but it appears the bugged popup is already at maximum, it won't go any higher no matter which option I pick there. Something must be limiting it? Changing the `overflow-y` setting enables me to view the hidden part by using scrollbars, but I can't get the popup any bigger that way either.

![1](https://user-images.githubusercontent.com/13466852/106326757-469c1400-627d-11eb-9b6f-4924c5ca2cf5.png)

![2](https://user-images.githubusercontent.com/13466852/106326760-4865d780-627d-11eb-9e63-0f383b890b78.png)

**Comment by erosman** [comment]
The maximum size of a popup is 800x600 AFA I recall.

Is the width OK now? or is it still too wide?

The height was never set and it is automatic.

Have you changed anything in Firefox e.g. userChrome.css?

Is it the standard Firefox?
Current version is Firefox 85? Try upgrading and see.

**Comment by Tharn** [comment]
Unfortunately, I have to stick to 84.0.2 for now as I need Flash for work.
But I have tried a new profile, which does not use the same userChrome.css as default. And I tried it with and without that file too, makes no difference as it's all tab bar tweaks.

It's a little less wide now, that's fine.

**Comment by Tharn** [comment]
Ok, at least on the laptop (where the issue is) I was able to upgrade to 85, and it's still the same thing. Tested in a new profile.

**Comment by erosman** [comment]
If you find any other info or if anyone else has a similar problem to give me a clue, I will fix it.

**Comment by Tharn** [comment]
Well, we can see from the comparison that your popup has more condensed options. The 3 fields at the bottom take up little vertical space, while the 2 visible ones for me take up more. So it's not just simply the popup that is drawn differently, but the dimensions of stuff inside of it. If your code doesn't account for this possibility and that's in fact a bug, too, maybe that results in wonky looks.

Another idea is that for both me and rubaboo, the popup almost reaches down to the tab bar. Possibly firefox restricts the max vertical height of the popup automatically.

**Comment by erosman** [comment]
As you can see form this image, even when Firefox window is made small, the popup shows without an problems.

![image](https://user-images.githubusercontent.com/6458876/106360045-a3ee9e80-632b-11eb-9e83-d1e4293f4799.png)

Additively, the problem is not reported by anyone else on normal unscaled screen. There must be an incompatibility, bug or something.

It might be a setting in Firefox that is different. You can try comparing the setting in `about:config` between the 2 computers to see if there is anything there.

**Comment by Tharn** [comment]
about:config is wiped using a new profile though. A fresh profile that gives me this issue really is the limit case for it having anything to do with the particular machine. I don't know what else to do here.

The only thing I that persists with a new profile is that Firefox on this machine is forced to render in software due to a graphics HW bug. Maybe you can see if this is reproducible at all in software mode.

**Comment by erosman** [comment]
> I can reproduce similar behavior on the other machine by putting Firefox in windowed mode and making the window flat enough that the popup would intersect with the task bar.

That is understable since there is no more room for it to grow.

Out of curiosity... try this

Go back to the debugger...

later these 2 values that control the height on the 2 sections that lists scripts

line 157: height: 10em;
line 163: height: 22em;


BTW, did you even try the standard default fonts?
Some custom fonts may have different height values.

**Comment by Tharn** [comment]
I tried the standard fonts, but it won't change anything.
I can't find these two lines anywhere. And it's really difficult to deal with the debugger on a 12" screen while having the popup open too. What I did find out playing around with the "fonts" setting though is that this looks way better for me with a smaller font size. The only thing that remains buggy is the cutoff which is too high above the task bar.

![3](https://user-images.githubusercontent.com/13466852/106362396-e52e8080-6322-11eb-9206-894538ccbc36.png)

**Comment by erosman** [comment]
> I can't find these two lines anywhere.

In the Debugger -> Style Editor `popup.css`


Oh, are you saying that the popup touches that taskbar and that is the reason it cuts off?
I though it cuts off while having enough space.
That is a different matter.

**Comment by Tharn** [comment]
Nevermind, I just checked it again with a very flat window. It does limit itself to a 15 pixel gap between the display edge or the task bar and the popup. In fullscreen, there is a 106 pixel gap even though the popup is cut off. So my theory was wrong.

Lowering the value at line 157 makes the whole content move upwards, to the point that it will properly display. As it shrinks further, the popup window shrinks along.

Lowering the value at line 163 makes the lower part of the content move up, from 'Script Commands' down to the option buttons. Leaving white space underneath as it shrinks. The popup doesn't shrink.

Increasing either value makes more of the contents slide down and disappear. It doesn't change the size of the popup.

**Comment by erosman** [comment]
What I dont understand is why you have problem on 1280x800

My laptop resolution is 1366x**768** which is narrower than your **800** but it shows the popup fine.

![image](https://user-images.githubusercontent.com/6458876/106367195-1d9b8200-6356-11eb-95c0-e2a617621fea.png)

**Comment by Tharn** [comment]
I can tell from that screenshot that all my popup fonts are bigger and all the margins are bigger too. I have "pages can use their own fonts" checked, so... why would firemonkey use way different margins / font sizes?

**Comment by erosman** [comment]
Have you changed the default zoom?

![image](https://user-images.githubusercontent.com/6458876/106367893-35c1d000-635b-11eb-8435-943430982319.png)

**Comment by Tharn** [comment]
No, default zoom is 100% as is system DPI.

**Comment by erosman** [comment]
Looking at **📣 Script Commands** the Unicode speaker also looks different which means a different font is used.

Can you post a full screenshot?

**Comment by Tharn** [comment]
Here are the screenshots. Looks like 3 different sets of icon between your screenshot and my 2.

![laptop](https://user-images.githubusercontent.com/13466852/106395965-66f6da80-6405-11eb-930a-9b0bdb4bc274.png)

![desktop](https://user-images.githubusercontent.com/13466852/106395969-69f1cb00-6405-11eb-94cc-187c497ccbc7.png)

**Comment by erosman** [comment]
Different icons means different fonts and that could be the reason for the issue you are experiencing.

- set the same fonts on both
- make sure the same font is also exists in the system
- 
I use the default fonts. The popup set to San-serif font which become Arial (as per Firefox font options).
You had set the San-serif to Calibri. Different fonts take different spaces i.e. width, height of characters.
Try Arial (default) and see.

**Comment by Tharn** [comment]
It makes very little difference. The icons stay the same, the fonts change, the popup is too small. Whether I use Calibri, Segoe UI, Default or another font. No matter if I set a small default size and override page fonts or not.

Again, I agree, but _this problem case should be covered by trying it with a fresh profile_, which I did.

**Comment by erosman** [comment]
I also tried with Calibri and it didn't cause any problems.

- The font size is larger on the popup that has problem. Both width & height are bigger which resulted in the problem.
- There is enough room at the bottom, so that is not the problem.


The problem is clearly shown in your screenshot from before.

My pop-up (300x562.7)
Width is set to 25em which is 300 ÷ 25 = 12px
![image](https://user-images.githubusercontent.com/6458876/106397502-0b3b4a00-6423-11eb-8f72-1af9acbfe839.png)


Your pop-up (413x660)
Width is set to 25em which is 413 ÷ 25 = 16.5px
![image](https://user-images.githubusercontent.com/6458876/106397515-28701880-6423-11eb-9cc3-7b65224847b5.png)


The reason for the cut-off is 660px in above since the max allowed for the pop-up is 600px.
Your pop-up font size is 16.5 instead of 12 and that is the problem.

The question remains ... why does that happen?
I have no idea ATM. :man_shrugging:

**Comment by Tharn** [comment]
Hey, thanks for trying to help but I gave up now.

Font size 16 is default for FF, maybe browser overrides the extension setting somehow.
Also, again, all this happens with a new profile. No other extensions, no settings, nothing.

**Comment by erosman** [comment]
Although I still don't know why your popup font is larger, I am going to hardcode some CSS values to ensure consistency in the next upgrade.

**Comment by erosman** [comment]
v2.18 uploaded. Let me know how it works out.

**Comment by Tharn** [comment]
Looking good. The icon set is still different (red megaphone etc.) but everything fits inside the popup now.
